version: '3.7'

networks:
  default:

volumes:
  redis:
  letsencrypt:

services:
  nginx:
    image: ${NGINX_IMAGE}
    deploy:
      mode: global
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - node

  redis:
    image: 'redis:5-alpine'
    volumes:
      - redis:/data

