version: '3.7'

services:
  nginx:
    environment:
      DOMAIN_URL: ${BRIDGE_URL}
      NODE_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      NODE_DOCKER_NAME: node
      NODE_PORT: 5000
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443

  node1:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node2:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node3:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node4:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node5:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
